title: F. Javier Rodríguez-Román
description: Economist
logo: assets/images/formal_picture.jpg
google_analytics: UA-181040919-1
github:
  is_project_page: false
theme: jekyll-theme-minimal
#baseurl: /frarodri.github.io
