title: F. Javier Rodríguez-Román
description: Economist
logo: assets/images/formal_picture_new.JPG
footer: New footer
google_analytics: UA-181040919-1
github:
  is_project_page: false
theme: jekyll-theme-minimal
